### ISSUE TITLE
AssertionError when trying to start a local ray cluster with 1 head node and 1 worker node

### ISSUE THREAD

**Issue by SecretSettler** [ServerlessLLM/ServerlessLLM#44]
After the installation, I tried to run the command shown in the doc:
```bash
ray start --head --port=6379 --num-cpus=4 --num-gpus=0 \
--resources='{"control_node": 1}' --block
```
Then I encountered the following error about the potential Redis connection:

ray start --head --port=6379 --num-cpus=4 --num-gpus=0 --resources='{"control_node": 1}' --block
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 10.0.0.5
Traceback (most recent call last):
  File "/home/a100user/miniconda3/envs/sllm/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2498, in main
    return cli()
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/ray/scripts/scripts.py", line 771, in start
    node = ray._private.node.Node(
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/ray/_private/node.py", line 306, in __init__
    self.start_head_processes()
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/ray/_private/node.py", line 1311, in start_head_processes
    self._write_cluster_info_to_kv()
  File "/home/a100user/miniconda3/envs/sllm/lib/python3.10/site-packages/ray/_private/node.py", line 1266, in _write_cluster_info_to_kv
    assert curr_val == self._session_name.encode("utf-8"), (
AssertionError: Session name session_2024-07-28_08-51-18_117800_2275776 does not match persisted value b'session_2024-07-20_08-59-23_126414_786616'. Perhaps there was an error connecting to Redis.

**Comment by SecretSettler** [comment]
To update:
I found that this issue may be caused by an already-started ray server on my cluster.
